mozilla/standup

standup/templates/landings/help.html

Adding just a teensy bit of help - letting people know that they can send !help to the IRC bot for help. That will make things much easier for new humans like me.

Adding some help

---

.travis.yml
Makefile
requirements-dev.txt
setup.cfg
standup/status/tests/test_utils.py

Fixes pytest setup and updates it to 3.0.1.

Pytest fixes

---

.gitignore
Makefile
bin/phb-manage.sh
bin/run-common.sh
bin/run-tests.sh
docker-compose.yml
docker/standup_base
etc/supervisord.conf
standup/api/admin.py
standup/settings.py
standup/status/admin.py
standup/status/migrations/0001_initial.py
standup/status/models.py
standup/user/admin.py
standup/user/migrations/0001_initial.py
standup/user/migrations/0002_add_standup_user.py
standup/user/migrations/0003_legacy_db_move.py
standup/user/models.py

* Improve Django admin
* Enable security settings
* Changes to docker required for Heroku
Fix #178

Add db migrations for legacy database

---

standup/settings.py

We've filed a but to get an SSL cert. This gets us ready for turning that on.

Prep for SSL

---

standup/status/jinja2/base.html

Add temporary "Standup v2!" announcement line

---

docker/standup_base

Fix npm install location

---

contribute.json
root_files/contribute.json
standup/settings.py

See https://www.contributejson.org/

Add contribute.json file for contribution discovery

---

standup/settings.py
standup/status/tests/test_views.py
standup/status/urls.py
standup/status/views.py

Add setting to turn off disallow. Mainly so that we can
tell robots not to index the staging instance.

Add /robots.txt

---

bin/run-prod.sh

Should help with our memory climbing issues

Add max-requests setting to gunicorn

---

standup/status/jinja2/base.html

And make the avatar in the menu bar a link to profile

Add admin link for admins

---

bin/phb-manage.sh
bin/run-tests.sh
standup/settings.py
standup/status/jinja2/users/login.html
standup/status/views.py

This switches the code around so that Auth0 is not required. If the
configuration is not available, then signin is disabled.

Change Auth0 so it's not required

---

standup/status/migrations/0008_github_handle_fixes.py
standup/status/models.py
standup/status/views.py

Make github_handle optional and drop unique requirement

---

standup/settings.py

Nix the cache-backed sessions

---

standup/auth0/pipeline.py

If auth0 returns a nickname that wasn't unique, then create_user would throw an
IntegrityError. This changes it to try a sequence.

Fix create_user

---

standup/status/management/commands/finduser.py

This command looks at a bunch of User and StandupUser fields for a string and
then spits out a table of information for all the users that match in some way.
It's totally not wildly interesting, but it'll probably help a bunch plus it gives us something to iterate on going forward to make our lives easier.

Add rough finduser command

---

standup/status/jinja2/base.html
standup/status/jinja2/status/search.html
standup/status/search.py
standup/status/static/less/style.less
standup/status/tests/test_search.py
standup/status/urls.py
standup/status/views.py

This uses a self-written tokenizer which doesn't support parens and other
things. It's not very good. But probably a good enough first pass to start
iterating with.
Fixed #164.

First pass at search

---

standup/status/forms.py
standup/status/jinja2/includes/macros.html
standup/status/jinja2/status/user.html
standup/status/jinja2/users/profile.html
standup/status/migrations/0010_populate_slug.py
standup/status/models.py

* add migration to make sure all users have a slug
* change @ mentions so that it always uses the slug rather than User.username
* remove all uses of User.username--we don't want to use this anymore
* add slug-editing to Profile page
Fixes #356.

Fix @ mentions

---

standup/status/admin.py
standup/status/migrations/0011_remove_content_html.py
standup/status/models.py

We weren't using it anywhere, so this is just removing it from the model.
This fixes #208.

Remove content_html

---

Makefile
README.rst
docker-compose.yml
tests/smoketest.py

This is good enough to build off of.
Fixes #275.

Implement really rough smoke tests

---

standup/status/management/commands/mergeuser.py
standup/status/tests/factories.py
standup/status/tests/test_commands.py

We're merging users that are on teams. This fixes mergeuser so that it handles
teams correctly.
Fixes #344.

Add team-handling to mergeuser

---

standup/status/jinja2/base.html
standup/status/jinja2/status/search.html
standup/status/jinja2/users/login.html

* remove status post form on search page
* remove white bar on signin page
Fixes #355.

Some ui fixes

---

requirements-dev.txt
standup/status/admin.py
standup/status/jinja2/status/team.html
standup/status/management/commands/mergeuser.py
standup/status/migrations/0012_teamusercopy.py
standup/status/migrations/0013_backup_teamuser.py
standup/status/migrations/0014_remove_teamuser.py
standup/status/migrations/0015_team_users.py
standup/status/migrations/0016_restore_teamuser.py
standup/status/models.py
standup/status/tests/test_commands.py

Teamuser fix

---

bin/deploy.sh

@pmac Does this look right? I think this is preventing standupstage from deploying.

Fix deploy to deploy local/standup_base image

---

requirements.txt
standup/api/urls.py
standup/api/views.py
standup/settings.py
standup/status/jinja2/base.html
standup/status/templatetags/filters.py

Also add an API endpoint for the messages.

Issue #236: Add broadcast messages via the admin
