.travis.yml
bin/deploy.sh
bin/run-tests.sh
bin/travis-docker-cache.sh
docker-compose.yml
standup/settings.py

It's actually the Gzip Manifest staticfiles storage that barfs if the files are missing. I think this is a fine fix for this (we also do this in bedrock) since I don't think static files should be required for python unittests, but I'm happy to hear a differing opinion.

Fix #173: Use default staticfiles storage for tests

---

standup/status/jinja2/500.html

This nixes use of "settings" in the 500 template. For some reason,
that was causing it to bomb out. This also nixes anything that might
kick off a db query.
I think this will fix #233. If not, it'll get us closer.
Turns out it's super hard to write tests that correctly test the "unhandled exception was thrown" situation because the Django TestClient makes it impossible and DEBUG mode shows you something other than your 500 template.
If we're intent on testing this in the unit test suite, then we might have to write our own mini-test client somehow.

Rework 500 template

---

standup/status/models.py

Some slugs for things in the database apparently don't match the slug regex. So when trying to display those it will rightly throw a NoReverseMatch exception.  This deals witht those by simply moving on since those are anomalies or the result of XSS testing.

Fix NoReverseMatch errors

---

docker/standup_base
package.json
standup/pipeline.py
standup/settings.py

Switching from the seemingly abandoned yuglify to:
* [clean-css](https://www.npmjs.com/package/clean-css)
* [uglify-js](https://www.npmjs.com/package/uglify-js)
This is what MDN is currently using and what bedrock is likely switching to shortly.

Switch JS and CSS compressors

---

standup/settings.py
standup/status/middleware.py

e.g. requests to https://standups.herokuapp.com would redirect to https://www.standu.ps if we set ENFORCE_HOSTNAME=www.standu.ps.

Add middleware to enforce a hostname of our choice

---

standup/settings.py

On a side-note, all configs default to either 'true' or 'false', which I found _slightly_ confusing.
I suppose 'True' and 'False' (still quoted, by uppercase) would be a bit more pythonic. 
I'll file another PR should we care enough to change this (cc @pmac to decide this :))

This should add the X-Content-Type: nosniff header

---

standup/settings.py

This sets the X-Frame-Options header to SAMEORIGIN for every outgoing HttpResponse according to the [django docs](https://docs.djangoproject.com/en/1.9/ref/clickjacking/#how-to-use-it)

Add XFrameOptionsMiddleware (see #224)

---

standup/status/tests/test_views.py
standup/status/views.py

View for an individual status was throwing an error from the paginator when the queryset was empty. This change forces the 404.
Note: We have to use the paginator even for this page because of what the macros that display statuses expect.

Individual status page 404 instead of 500

---

standup/settings.py
standup/urls.py

This should fix this issue. The error views included with django-jinja use normal view context instances.

Fix error pages not having context-processor data

---

standup/settings.py

We're running out of memory in prod constantly. My current theory is
that our cache settings are such that we're using an increasing amount
of cache until we pass the threshold for memory allowance.
Assuming that's correct, limiting the caching by number of entries and
timeout should make that better.
This implements that.

Tweak cache settings for better memory usage

---

standup/status/jinja2/status/statistics.html
standup/status/static/less/style.less
standup/status/tests/test_views.py
standup/status/urls.py
standup/status/views.py

This is a rough statistics page that shows a snapshot of Standup stuff.
It's rough in that it's not very pretty and it's not wildly informative.
But we can use this to build a better page that's more helpful.
This has some of the things in #267, but not everything. Regardless, I think I'm going to say this fixes #267 and we can add additional statistics as we have requirements for them.

Add rough statistics page

---

standup/status/models.py

We use the same Markdown instance for all convert calls. Per the
Markdown docs, we need to call .reset() between convert calls so as to
reset the Markdown converter state and thus avoid performance
degredation over time.
https://pythonhosted.org/Markdown/reference.html#Markdown
This does that.
This also has a HUGE effect on memory and response time performance.

Fix markdown call

---

standup/status/views.py

Right now, it's kicking up an error that suggests it's missing context. It worked fine locally and in the tests, so I'm puzzled.
Regardless, this tweaks the code a bit to see if it's better.

Fix statistics page rendering

---

standup/status/jinja2/base.html

This notice is temporary. At this point, we're pretty far into Standup v2 that
we don't need it anymore.

Remove Standup v2 announcement notice

---

standup/status/models.py
standup/status/tests/factories.py
standup/status/tests/test_models.py
standup/status/tests/test_utils.py

Turns out bleach is meant to understand HTML, not Markdown.  Also add some tests for the rest of the htmlify method.

Fix #321: Do bleach linkify after markdown->html

---

bin/run-tests.sh
requirements.txt
setup.cfg
standup/settings.py
standup/status/tests/conftest.py

* moves things around in requirements file making it more convenient to just
do "hashin blah requirements.txt" and have the thing be in the right section
* remove things from setup.cfg that weren't doing anything
* centralize settings-related configuration into bin/run-tests.sh
* switch tests from using dummy cache to locmem cache which requires we clear
the cache before every test

Cosmetic: clean up tests and requirements file

---

standup/wsgi.py

This is mentioned at the bottom of the Django section here:
https://devcenter.heroku.com/articles/memcachier#django
> Finally, we also strongly recommend that you place the following code in your wsgi.py file to correct a serious performance bug (#11331) with Django and memcached. The fix enables persistent connections under Django, which by default uses a new connection for each request:
>
> ```
> # Fix django closing connection to MemCachier after every request (#11331)
> from django.core.cache.backends.memcached import BaseMemcachedCache
> BaseMemcachedCache.close = lambda self, **kwargs: None
> ```

Add monkeypatch to prevent connection closing for memcachier

---

requirements.txt
standup/auth0/README.rst
standup/auth0/middleware.py
standup/auth0/tests/test_middleware.py
standup/settings.py
standup/status/urls.py
standup/status/views.py
standup/wsgi.py

This fixes everything for issue #334:
1. removes all caching and page caching
2. switches us back to using locmem
3. removes all the memcached stuff
4. changes auth0 `id_token` renewal to use the db and not cache--but also adds an untested cache-based middleware
@pmac Quick r?

Cache reworking

---

standup/status/migrations/0005_add_team_user_id.py

When we migrated the Standup data from the old db schema to the new one, we
skipped the 0001_initial migration because we already had a bunch of tables and
data. However, we needed to make changes to those tables.
This migration adds an "id" column to the team table, but it already has one
from the 0001_initial migration.
Given that this migration is only helpful when updating an old Standup db, I
commented out the code and turned it into a no-op.
This fixes #317.

Fix the 0005_add_team_user_id migration

---

standup/status/jinja2/base.html

We're transitioning auth methods again, so this helps notify users. There's
another issue for building in a messaging system that's db-backed, so we don't
have to keep doing this, but that's not done, yet.

Add hard-coded message

---

standup/api/tests/test_views.py
standup/api/urls.py
standup/api/views.py

The update API endpoint needs to be rewritten. This disables it until we do
that.

Disable update API

---

standup/api/tests/test_views.py
standup/api/views.py
standup/status/admin.py
standup/status/forms.py
standup/status/management/commands/finduser.py
standup/status/migrations/0009_remove_standupuser_github_handle.py
standup/status/models.py
standup/status/tests/factories.py

We stopped using it a while back when we switched to auth0, but we kept it
around in case it helped us merge user accounts. I haven't found it helpful so
far, so this removes it.

Remove github_handle

---

standup/auth0/pipeline.py
standup/auth0/tests/test_pipeline.py
standup/status/auth.py

This changes the auth0 code from using the `user_info['nickname']` field for
usernames and instead generating the username from hashing the email address
which we're using as a unique identifier. This fixes all kinds of problems.
The only part of this that affects Standup is the part where we're generating User instances with a fresh username. Otherwise we don't use the username anywhere including when matching OIDC identities to Standup identities.
Fixes #349.

Switch from nickname-based username to a hash

---

standup/auth0/pipeline.py

If email_verified isn't in user_info, treat it as if it were False.
Fixes #362.

Fix email check

---

Makefile
docker-compose.build.yml
docker-compose.yml
docker/standup_base
docker/standup_dev

Turns out using tini as the entrypoint does not work with Heroku's Docker container runtime. Also I am now more a fan of Debian images than Alpine.
This does move back to having NodeJS installed in the production container, and we could move back to not having that, but I don't see it as a big enough deal to bother with switching to that at present. If anyone feels differently please let me know.

Switch dockerfile base to mozmeao/base:pythode-3.6-6.10

---

.pyup.yml

Hey @willkg.
Looks like the requirement files were missing a `:`, causing the parsing to fail completely. This was also wrong in the docs, all blame on me!
I'll add a basic online linter like the one from [travis](http://lint.travis-ci.org/) to make this easier. In the meantime you can try to validate it here: http://yaml-online-parser.appspot.com/

Fix .pyup.yml

---

requirements.txt

This picks up the fix for infinite redirect on login when the OIDC OP
returns an error, but the Django session is still valid thus causing
the user to enter a nether-void between two realities from which they
can't escape except by tossing their cookies.
Fixes #412

Update mozilla-django-oidc to 0.6.0

---

standup/status/static/less/style.less

This makes the "what's your status?" textarea vertically resizable with a handle, with `resize` style.
The minimum and initial height is the current height.
This works on Firefox, Safari, and Chrome, but not on Edge.
https://developer.mozilla.org/en-US/docs/Web/CSS/resize
Given that it's optional enhancement feature, would it be fine?
The resize handle is partially hidden because the textarea has round border, but it's almost visible on above supported browsers (tested on macOS, debian with xfce, and windows 10)
I've first tried making it also horizontally resizable, but it has unexpected behavior because the textarea is aligned to the right.
So, if I grab the handle at the bottom-right of the textarea and drag it to right, the left side of the textarea grows to the left.
so I'd like to …

Fix #457: Make textarea vertically resizable
